version: '2'
services:

    storage:
        volumes:
            - ${HUMBLE_DATA}/production/mysql-data:/var/lib/mysql
            - ${HUMBLE_DATA}/production/wp-content:/var/www/html/wp-content

    mysql:
        restart: always

    wordpress:
        restart: always

    cache:
        image: nginx:1.11
        volumes:
            - ./services/cache/config/nginx.conf:/etc/nginx/nginx.conf
            - ${HUMBLE_DATA}/production/proxy-cache:/tmp/nginx
        links:
            - wordpress:app
        mem_limit: ${MEM_LIMIT_CACHE}
        restart: always

    proxy:
        image: nginx:1.11
        volumes:
            - ./services/proxy/config/nginx.conf:/etc/nginx/nginx.conf
            - ./services/proxy/config/server-configs-nginx:/etc/nginx/server-configs-nginx
            - ${HUMBLE_DATA}/production/wp-content:/var/www/static/wp-content
            - ./services/wordpress/wp-content/themes/docker:/var/www/static/wp-content/themes/docker
            - ./services/wordpress/wp-content/plugins/post-gallery-lite:/var/www/static/wp-content/plugins/post-gallery-lite
        links:
            - ${PROXY_TO}:app
        ports:
            - ${HUMBLE_PORT}:80
        mem_limit: ${MEM_LIMIT_PROXY}
        restart: always
