version: '2'
services:

    storage:
        image: busybox:1.25
        volumes:
            - ${HUMBLE_DATA}:/data
            - ${HUMBLE_BACKUP}:/backup

    mysql:
        image: mysql:5.7
        volumes_from:
            - storage
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress

    wordpress:
        build: ./services/wordpress
        links:
            - mysql:mysql
        ports:
            - ${HUMBLE_PORT}:80
        volumes_from:
            - storage
        environment:
            - WORDPRESS_DB_PASSWORD=root

    humble:
        image: marcopeg/humble:2.0.0
        volumes_from:
            - storage
        env_file:
            - .env
