version: '2'
services:

    storage:
        volumes:
            - ${HUMBLE_DATA}/production/mysql-data:/var/lib/mysql
            - ${HUMBLE_DATA}/production/wp-content:/var/www/html/wp-content

    mysql:
        volumes:
            - ./services/mysql/my.cnf:/etc/mysql/my.cnf
        mem_limit: 25m
        restart: always

    wordpress:
        mem_limit: 50m
        restart: always
