version: '2'
services:

    storage:
        volumes:
            - ${HUMBLE_DATA}/production/mysql-data:/var/lib/mysql
            - ${HUMBLE_DATA}/production/wp-content:/var/www/html/wp-content

    mysql:
        restart: always

    wordpress:
        restart: always

    proxy:
        image: nginx
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./services/nginx/h5bp:/etc/nginx/h5bp
            - ${HUMBLE_DATA}/production/proxy-cache:/tmp/nginx
            - ${HUMBLE_DATA}/production/wp-content:/var/www/static/wp-content
        links:
            - wordpress:wordpress
        ports:
            - ${HUMBLE_PORT}:80
        restart: always
