version: '2'
services:

    storage:
        volumes:
            - ${HUMBLE_DATA}/production/mysql-data:/var/lib/mysql
            - ${HUMBLE_DATA}/production/wp-content:/var/www/html/wp-content

    mysql:
        restart: always

    wordpress:
        restart: always
        # ports:
        #     - ${HUMBLE_PORT}:80


    proxy:
        image: nginx:1.11
        volumes:
            - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./services/nginx/config/server-configs-nginx:/etc/nginx/server-configs-nginx
            # - ./services/nginx/config/h5bp:/etc/nginx/h5bp
            - ${HUMBLE_DATA}/production/proxy-cache:/tmp/nginx
            - ${HUMBLE_DATA}/production/wp-content:/var/www/static/wp-content
            - ./services/wordpress/wp-content/themes/docker:/var/www/static/wp-content/themes/docker
            - ./services/wordpress/wp-content/plugins/post-gallery-lite:/var/www/static/wp-content/plugins/post-gallery-lite
        links:
            - wordpress:wordpress
        ports:
            - ${HUMBLE_PORT}:80
        restart: always
