version: '2'
services:

    storage:
        volumes:
            - ./data/dev-mysql-data:/var/lib/mysql
            - ./data/dev-wp-content:/var/www/html/wp-content
            - ./services/wordpress/wp-content/themes/docker:/var/www/html/wp-content/themes/docker
            - ./services/assets:/usr/src/app

    wordpress:
        build:
            context: ./services/wordpress/
            dockerfile: Dockerfile.development
        ports:
            - 8080:80

    assets:
        image: marcopeg/node:0.1
        volumes_from:
            - storage
        environment:
            - BUILD_TARGET=/var/www/html/wp-content/themes/docker
        entrypoint:
            - npm
            - start

    pma:
        image: phpmyadmin/phpmyadmin:4.6.4-1
        links:
            - mysql:db
        ports:
            - 8081:80
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=root
