version: '2'
services:

    pma:
        image: phpmyadmin/phpmyadmin:4.6.4-1
        links:
            - mysql:db
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=root
